/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCca3RouteImport } from './routes/country.$cca3'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCca3Route = CountryCca3RouteImport.update({
  id: '/country/$cca3',
  path: '/country/$cca3',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/country/$cca3': typeof CountryCca3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/country/$cca3': typeof CountryCca3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/country/$cca3': typeof CountryCca3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/country/$cca3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/country/$cca3'
  id: '__root__' | '/' | '/country/$cca3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountryCca3Route: typeof CountryCca3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$cca3': {
      id: '/country/$cca3'
      path: '/country/$cca3'
      fullPath: '/country/$cca3'
      preLoaderRoute: typeof CountryCca3RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountryCca3Route: CountryCca3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
